-- Create user_settings table
CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE,
    theme VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_user_settings PRIMARY KEY (id),
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Insert default settings for existing users
INSERT INTO user_settings (user_id, theme, created_at, updated_at)
SELECT id, 'SYSTEM', NOW(), NOW() FROM users;
