services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=horizon'
      - 'POSTGRES_PASSWORD=horizon'
      - 'POSTGRES_USER=horizon'
    ports:
      - '5433:5432'
    volumes:
      - ./database/postgres:/var/lib/postgresql/data